export const SELECT_SPRINT = 'SELECT_SPRINT';
export const SHOW_ADD_SPRINT_MODAL = 'SHOW_ADD_SPRINT_MODAL';
export const SHOW_EDIT_SPRINT_MODAL = 'SHOW_EDIT_SPRINT_MODAL';
export const HIDE_SPRINT_MODAL = 'HIDE_SPRINT_MODAL';
export const ADD_SPRINT = 'ADD_SPRINT';
export const DELETE_SPRINT = 'DELETE_SPRINT';
export const EDIT_SPRINT = 'EDIT_SPRINT';