export const SELECT_SPRINT = 'SELECT_SPRINT';
export const SHOW_ADD_SPRINT = 'SHOW_ADD_SPRINT';
export const HIDE_ADD_SPRINT = 'HIDE_ADD_SPRINT';
export const ADD_SPRINT = 'ADD_SPRINT';
export const DELETE_SPRINT = 'DELETE_SPRINT';
export const EDIT_SPRINT = 'EDIT_SPRINT';